env:
  browser: true
  es2021: true
  jest: true

extends:
  - plugin:prettier/recommended

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - "@typescript-eslint"
  - 'unused-imports'
  - simple-import-sort
  - prettier

settings:
  import/resolver:
    typescript:

  react:
    version: detect

ignorePatterns:
  - "dist/**"
  - "*.config.js"

"overrides":
  - files:
    - "*.ts"
    - "*.tsx"

rules:
  "prettier/prettier": error
  "simple-import-sort/imports": error
  "simple-import-sort/exports": error
  "unused-imports/no-unused-imports-ts": 2
  
